# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "🔥 Feature-rich interactive Jira command-line"
  homepage "https://github.com/markiannucci/jira-cli"
  version "1.6.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/MarkIannucci/jira-cli/releases/download/v1.6.2/jira_1.6.2_macOS_x86_64.tar.gz"
      sha256 "d4f2445b7268aa14d0daf3edcf5233ba2d88328b0fb164a3f9b3a3256a65a697"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
      end
    end
    on_arm do
      url "https://github.com/MarkIannucci/jira-cli/releases/download/v1.6.2/jira_1.6.2_macOS_arm64.tar.gz"
      sha256 "f5c97e5333861e1c24f7025057711a1b41e2da145ca805fe75b84d1cb3a1c702"

      def install
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MarkIannucci/jira-cli/releases/download/v1.6.2/jira_1.6.2_linux_x86_64.tar.gz"
        sha256 "be23615ff2a9cc91e2e93e41bb63a83b42424d7302708d1a467525754456c2a4"

        def install
          if build.head?
            system "make", "install"
            bin.install ENV["GOPATH"] + "/bin/jira"
          else
            bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
          end
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/MarkIannucci/jira-cli/releases/download/v1.6.2/jira_1.6.2_linux_armv6.tar.gz"
        sha256 "ec0b6c152204cd29c8283b5b7a6bb7a03beda9ab90448d383fa7c90e24ce2fa2"

        def install
          if build.head?
            system "make", "install"
            bin.install ENV["GOPATH"] + "/bin/jira"
          else
            bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MarkIannucci/jira-cli/releases/download/v1.6.2/jira_1.6.2_linux_arm64.tar.gz"
        sha256 "23c1ad8e11d4ace1dc250943bd44ecb330c99ccfba4e2ccb3669a60c84394901"

        def install
          if build.head?
            system "make", "install"
            bin.install ENV["GOPATH"] + "/bin/jira"
          else
            bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
          end
        end
      end
    end
  end

  head do
    url "https://github.com/markiannucci/jira-cli.git", branch: "main"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/jira version")
    assert_includes help_text, "Version=\"#{version}\""
  end
end
